[build]
  publish = "public"

[[edge_functions]]
path = "/dns-query"
function = "dns"

[[edge_functions]]
path = "/resolve"
function = "dns"

[[edge_functions]]
path = "/ip"
function = "dns"

[[edge_functions]]
path = "/ip-info"
function = "dns"
